// MongoDB Initialization Script
// Generated by ProjexLight CLI Export System
// Project: Leadpulse MCP
// Database: mongodb
// Auto-executed when Docker container is first created
// Location: ./init-scripts/01-schema.js
// Schema Hash: e10808d43975dc40

// ========================================
// SWITCH TO APPLICATION DATABASE
// ========================================
db = db.getSiblingDB('leadpulse_mcp_db');

// ========================================
// SCHEMA VERSION TRACKING (For Multi-Developer Sync)
// ========================================
// This collection tracks the current schema version in your local database.
// The MCP Schema Sync Agent uses this to detect changes and sync with ProjexLight.

db.createCollection('_schema_version');
db._schema_version.insertOne({
  schema_hash: 'e10808d43975dc40',
  version: 1,
  applied_at: new Date(),
  source: 'init'
});

// ========================================
// CREATE COLLECTIONS WITH VALIDATION
// ========================================

// Schema: Leadpulse MCP Schema
// Auto-generated database schema for Leadpulse MCP. Generated from project description...

// Create Users collection
db.createCollection('users');
db.users.createIndex({ created_at: -1 });

// Create Campaigns collection
db.createCollection('campaigns');
db.campaigns.createIndex({ created_at: -1 });

// Create Contacts collection
db.createCollection('contacts');
db.contacts.createIndex({ created_at: -1 });

// Create Campaign_status collection
db.createCollection('campaign_status');
db.campaign_status.createIndex({ created_at: -1 });

// ========================================
// SAMPLE DATA (Optional)
// ========================================
// Uncomment and modify the following to add sample data:

// db.users.insertOne({ field1: 'value1', field2: 'value2', created_at: new Date(), updated_at: new Date() });
// db.campaigns.insertOne({ field1: 'value1', field2: 'value2', created_at: new Date(), updated_at: new Date() });
// db.contacts.insertOne({ field1: 'value1', field2: 'value2', created_at: new Date(), updated_at: new Date() });
// db.campaign_status.insertOne({ field1: 'value1', field2: 'value2', created_at: new Date(), updated_at: new Date() });

// ========================================
// SCRIPT COMPLETED
// ========================================
print('MongoDB initialization completed for Leadpulse MCP');
